[package]
name = "gateway"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "gateway"
path = "src/main.rs"

[dependencies]
config.workspace = true
migrations.workspace = true
mdm.workspace = true

tokio.workspace = true
axum.workspace = true
tracing.workspace = true
anyhow.workspace = true
